import type { AuditResult } from '../types/audit.ts'
import { PILLAR_LABELS } from '../types/pillar.ts'
import { BLOCKER_UI_LABELS } from '../types/blocker.ts'

export function exportProblemList(auditResult: AuditResult): string {
  const lines: string[] = [
    '=== INERTIA LINTER — PROBLEM LIST ===',
    'DRAFT — Pending physician review',
    'SYNTHETIC DATA ONLY',
    '',
    `EF Category: ${auditResult.efCategory}`,
    `GDMT Score: ${String(auditResult.gdmtScore.normalized)}/100`,
    '',
  ]

  for (const pr of auditResult.pillarResults) {
    const label = PILLAR_LABELS[pr.pillar]
    lines.push(`* ${label}: ${pr.status}`)

    for (const blocker of pr.blockers) {
      lines.push(`  - Blocker: ${BLOCKER_UI_LABELS[blocker]}`)
    }

    for (const info of pr.missingInfo) {
      lines.push(`  - Missing: ${info}`)
    }
  }

  if (auditResult.nextBestQuestions.length > 0) {
    lines.push('')
    lines.push('Next Best Questions:')
    for (const q of auditResult.nextBestQuestions) {
      lines.push(`  - ${q}`)
    }
  }

  lines.push('')
  lines.push('Generated by Inertia Linter (Guideline-as-Code v2)')
  lines.push('DRAFT — Pending physician review')

  return lines.join('\n')
}
