import type { AuditResult } from '../types/audit.ts'
import type { PatientSnapshot } from '../types/patient.ts'
import { PILLAR_LABELS } from '../types/pillar.ts'
import { BLOCKER_UI_LABELS } from '../types/blocker.ts'

export function exportSOAP(
  auditResult: AuditResult,
  patient: PatientSnapshot,
): string {
  const pillarLines = auditResult.pillarResults
    .map((pr) => {
      const label = PILLAR_LABELS[pr.pillar]
      const blockerLabels = pr.blockers
        .map((b) => BLOCKER_UI_LABELS[b])
        .join(', ')
      const suffix = blockerLabels ? ` — ${blockerLabels}` : ''
      return `    - ${label}: ${pr.status}${suffix}`
    })
    .join('\n')

  const missingSection =
    auditResult.missingInfo.length > 0
      ? auditResult.missingInfo.map((m) => `    - ${m}`).join('\n')
      : '    (none)'

  const questionsSection =
    auditResult.nextBestQuestions.length > 0
      ? auditResult.nextBestQuestions.map((q) => `    - ${q}`).join('\n')
      : '    (none)'

  const egfrLine =
    patient.egfr !== undefined ? `, eGFR ${String(patient.egfr)}` : ''
  const kLine =
    patient.potassium !== undefined
      ? `, K+ ${String(patient.potassium)}`
      : ''

  return [
    '=== INERTIA LINTER AUDIT REPORT ===',
    'DRAFT — Pending physician review',
    'SYNTHETIC DATA ONLY',
    '',
    `S (Subjective): NYHA Class ${String(patient.nyhaClass)}`,
    `O (Objective): EF ${String(patient.ef)}%, SBP ${String(patient.sbp)}, HR ${String(patient.hr)}${egfrLine}${kLine}`,
    'A (Assessment):',
    `  EF Category: ${auditResult.efCategory}`,
    `  GDMT Score: ${String(auditResult.gdmtScore.normalized)}/100`,
    '  Pillar Status:',
    pillarLines,
    'P (Plan):',
    '  Missing Information:',
    missingSection,
    '  Next Best Questions:',
    questionsSection,
    '',
    'Generated by Inertia Linter (Guideline-as-Code v2)',
    'DRAFT — Pending physician review',
  ].join('\n')
}
